#!/usr/bin/env python3
# SPDX-License-Identifier: GPL-2.0-or-later

"""Generate RazeRS's evidence-only device catalog from a pinned iRazer tree."""

from __future__ import annotations

import argparse
import json
import re
import subprocess
from dataclasses import dataclass
from pathlib import Path


SCHEMA_VERSION = 1
SOURCE_REPOSITORY = "hanley-tech/iRazer"
SOURCE_COMMIT = "7cc856ddd26edd9523a12a540b6d95a4ea3a54c4"
SOURCE_LICENSE = "MIT"
CATALOG_PATH = Path("Sources/iRazer/DeviceCatalog.swift")

DEVICE_PATTERN = re.compile(
    r"\.init\(id:\s*(?:\"([^\"]+)\"|(nommoV2ID)),\s*"
    r"name:\s*\"([^\"]+)\",\s*"
    r"category:\s*\.(\w+),\s*"
    r"pid:\s*\"([0-9A-Fa-f]{4}):([0-9A-Fa-f]{4})\",\s*"
    r"support:\s*\.(\w+),\s*"
    r"capabilities:\s*\[([^\]]*)\],\s*"
    r"matrix:\s*\"([^\"]*)\",\s*"
    r"tx:\s*\"([^\"]*)\"\s*\)",
    re.DOTALL,
)


@dataclass(frozen=True)
class Device:
    source_id: str
    name: str
    kind: str
    vid: int
    pid: int
    upstream_support: str
    capability_labels: tuple[str, ...]
    matrix_family: str
    transaction_id: int


def verify_source(source: Path) -> None:
    result = subprocess.run(
        ["git", "-C", str(source), "rev-parse", "HEAD"],
        check=True,
        capture_output=True,
        text=True,
    )
    actual_commit = result.stdout.strip()
    if actual_commit != SOURCE_COMMIT:
        raise SystemExit(
            f"iRazer checkout is at {actual_commit}; expected pinned commit {SOURCE_COMMIT}"
        )


def normalize_kind(value: str) -> str:
    return {
        "accessories": "accessory",
        "gpus": "gpu",
        "headsets": "headset",
        "keyboards": "keyboard",
        "keypads": "keypad",
        "laptops": "laptop",
        "ledstrips": "led-strip",
        "mice": "mouse",
        "mousepads": "mouse-mat",
        "speakers": "speaker",
    }[value]


def load_devices(source: Path) -> list[Device]:
    path = source / CATALOG_PATH
    if not path.is_file():
        raise SystemExit(f"iRazer device catalog not found: {path}")

    swift = path.read_text(encoding="utf-8")
    devices = []
    for match in DEVICE_PATTERN.finditer(swift):
        (
            literal_id,
            nommo_id,
            name,
            raw_kind,
            raw_vid,
            raw_pid,
            support,
            raw_capabilities,
            matrix,
            transaction_id,
        ) = match.groups()
        capability_labels = tuple(re.findall(r'"([^"]+)"', raw_capabilities))
        devices.append(
            Device(
                source_id=literal_id or ("nommo-v2" if nommo_id else ""),
                name=name,
                kind=normalize_kind(raw_kind),
                vid=int(raw_vid, 16),
                pid=int(raw_pid, 16),
                upstream_support=support,
                capability_labels=capability_labels,
                matrix_family=matrix.lower().replace("_", "-"),
                transaction_id=int(transaction_id, 16),
            )
        )

    expected_count = swift.count(".init(")
    if len(devices) != expected_count:
        raise SystemExit(
            f"parsed {len(devices)} iRazer entries, but found {expected_count} initializers"
        )
    devices.sort(key=lambda device: (device.kind, device.name.casefold(), device.pid))
    identities = [(device.vid, device.pid) for device in devices]
    if len(identities) != len(set(identities)):
        raise SystemExit("iRazer source contains duplicate VID/PID identities")
    return devices


def toml_string(value: str) -> str:
    return json.dumps(value, ensure_ascii=False)


def toml_strings(values: tuple[str, ...]) -> str:
    return "[" + ", ".join(toml_string(value) for value in values) + "]"


def render(devices: list[Device]) -> str:
    lines = [
        "# SPDX-License-Identifier: GPL-2.0-or-later",
        "# Generated by tools/import_irazer.py; do not edit by hand.",
        "# Upstream support labels are iRazer claims, not RazeRS verification.",
        f"schema_version = {SCHEMA_VERSION}",
        "",
        "[source]",
        'name = "iRazer"',
        f"repository = {toml_string(SOURCE_REPOSITORY)}",
        f"commit = {toml_string(SOURCE_COMMIT)}",
        f"path = {toml_string(str(CATALOG_PATH.parent))}",
        f"license = {toml_string(SOURCE_LICENSE)}",
        'generated_by = "tools/import_irazer.py"',
    ]

    for device in devices:
        lines.extend(
            [
                "",
                "[[devices]]",
                f"source_id = {toml_string(device.source_id)}",
                f"name = {toml_string(device.name)}",
                f"kind = {toml_string(device.kind)}",
                f"vid = 0x{device.vid:04x}",
                f"pid = 0x{device.pid:04x}",
                f"upstream_support = {toml_string(device.upstream_support)}",
                f"capability_labels = {toml_strings(device.capability_labels)}",
                f"matrix_family = {toml_string(device.matrix_family)}",
                f"transaction_id = 0x{device.transaction_id:02x}",
                f"source_path = {toml_string(str(CATALOG_PATH))}",
                f"source_symbol = {toml_string('DeviceCatalog.all:' + device.source_id)}",
            ]
        )
    return "\n".join(lines) + "\n"


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--source", type=Path, required=True, help="iRazer checkout")
    parser.add_argument("--output", type=Path, required=True, help="catalog output path")
    args = parser.parse_args()

    verify_source(args.source)
    devices = load_devices(args.source)
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(render(devices), encoding="utf-8")
    print(f"imported {len(devices)} iRazer device records into {args.output}")


if __name__ == "__main__":
    main()
