[book]
title = "RazeRS Handbook"
authors = ["RazeRS contributors"]
language = "en"
src = "."

[build]
create-missing = false
build-dir = "../target/book/en"

[output.html]
site-url = "/razers/en/"
git-repository-url = "https://github.com/YangYuS8/razers"
edit-url-template = "https://github.com/YangYuS8/razers/edit/main/docs/{path}"
additional-js = ["theme/language.js"]
additional-css = ["theme/custom.css"]

[output.html.search]
enable = true
